algoritmo "semnome"
// Função :
// Autor :
// Data : 18/05/2023
// Seção de Declarações 
var
idade: inteiro
nome: caractere


inicio

//entrada

escreval( "digite seu nome: ")
leia (nome)

escreval( "digite sua idade: ")
leia (idade)


//processamento

se (idade >= 18) entao
 escreval (nome, "  voce e de maior, já pode ser preso")
 
senao
 escreval( nome, "  voce e de menor, eita novinho")
 
fimse

//saida


fimalgoritmo
