algoritmo "semnome"
// Função :
// Autor :
// Data : 18/05/2023
// Seção de Declarações 
var
salario, gasto: real


inicio

//entrada

escreval( "digite seu salario: ")
leia (salario)

escreval( "digite seu gasto mensal: ")
leia (gasto)


//processamento

se (gasto >= salario) entao
 escreval ("acabou o dinheiro, colega")
 
senao
 escreval( "saldo positivo")
 
fimse

fimalgoritmo
