algoritmo "Temperatura"
// Função : Verificar se a temperatura está fria, normal ou quente
// Autor :
// Data :
// Seção de Declarações
var

temperatura: real

inicio

escreval ("Digite o valor da temperatura:")
leia (temperatura)


//processamento

se (temperatura<20) entao
escreval (" friozinho.")

senao (temperatura<25)
escreval ("está bom")

senao
escreval ("Calorzao")

fimse


// Seção de Comandos
fimalgoritmo
